# Generated by Django 5.2.6 on 2025-09-24 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived"), ("draft", "Draft")],
                        default="draft",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("learning_resource_url", models.URLField(blank=True, null=True)),
                ("order_index", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "order_index"],
                "unique_together": {("course", "order_index")},
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("mcq", "Multiple Choice"), ("fillblank", "Fill in the Blank")],
                        max_length=20,
                    ),
                ),
                ("passing_score", models.PositiveIntegerField(blank=True, null=True)),
                ("order_index", models.PositiveIntegerField(default=0)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="courses.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter", "order_index"],
                "unique_together": {("chapter", "order_index")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("mcq", "Multiple Choice"), ("fillblank", "Fill in the Blank")],
                        max_length=20,
                    ),
                ),
                ("correct_answer_text", models.TextField(blank=True)),
                ("order_index", models.PositiveIntegerField(default=0)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.test",
                    ),
                ),
            ],
            options={
                "ordering": ["test", "order_index"],
                "unique_together": {("test", "order_index")},
            },
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=500)),
                ("order_index", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="courses.question",
                    ),
                ),
            ],
            options={
                "ordering": ["question", "order_index"],
                "unique_together": {("question", "order_index")},
            },
        ),
        migrations.CreateModel(
            name="UserCourse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enrollment_date", models.DateTimeField(auto_now_add=True)),
                ("is_dropped", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-enrollment_date"],
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="UserTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_date", models.DateTimeField(auto_now_add=True)),
                ("time_spent", models.PositiveIntegerField(default=0)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="courses.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-attempt_date"],
            },
        ),
        migrations.CreateModel(
            name="UserTestAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("given_answer_text", models.TextField(blank=True)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "user_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="courses.usertest",
                    ),
                ),
            ],
            options={
                "ordering": ["user_test"],
            },
        ),
    ]
