# Generated by Django 5.2.6 on 2025-09-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_premium",
        ),
        migrations.AddField(
            model_name="user",
            name="enable_email_notification",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_icon",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name="UserSettings",
        ),
    ]
